[[DeviceList]]
  Name = 'System-Performance'
  ProfileName = 'System-Performance-Profile'
  Description = 'System performance device'
  Labels = [ 'System performance' ]
  [DeviceList.Protocols]
  [DeviceList.Protocols.other]
    Address = 'simple01'
    Port = '300'
  [[DeviceList.AutoEvents]]
    Interval = '30s'
    OnChange = false
    SourceName = 'Temperature'
  [[DeviceList.AutoEvents]]
    Interval = '10m'
    OnChange = false
    SourceName = 'Storage'
  [[DeviceList.AutoEvents]]
    Interval = '10m'
    OnChange = false
    SourceName = 'RAM'
  [[DeviceList.AutoEvents]]
    Interval = '10m'
    OnChange = false
    SourceName = 'InternetSpeed'